name: RSS Feed to Markdown

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert_feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run RSS Feed to Markdown Action
        uses: keiranlovett/rss-feed-to-markdown@main
        with:
          feed_url: 'https://www.spurtr.eu/atom.xml?redirect=false&start-index=1&max-results=500'
          template_file: 'assets/template.md'
          output_dir: 'posts/'

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add posts/
          git commit -m "Add generated markdown files from RSS feed" || echo "No changes to commit"
          git push
